# Generated by Django 4.2.3 on 2023-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
