# Generated by Django 4.2.3 on 2023-07-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testcases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
                ('verdict', models.CharField(max_length=100)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=30)),
            ],
        ),
    ]
